/*
Core APIs

universalmacro

API version: 0.0.2
Contact: chenyunda218@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TencentCloudConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TencentCloudConfig{}

// TencentCloudConfig struct for TencentCloudConfig
type TencentCloudConfig struct {
	SecretId *string `json:"secretId,omitempty"`
	SecretKey *string `json:"secretKey,omitempty"`
}

// NewTencentCloudConfig instantiates a new TencentCloudConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTencentCloudConfig() *TencentCloudConfig {
	this := TencentCloudConfig{}
	return &this
}

// NewTencentCloudConfigWithDefaults instantiates a new TencentCloudConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTencentCloudConfigWithDefaults() *TencentCloudConfig {
	this := TencentCloudConfig{}
	return &this
}

// GetSecretId returns the SecretId field value if set, zero value otherwise.
func (o *TencentCloudConfig) GetSecretId() string {
	if o == nil || IsNil(o.SecretId) {
		var ret string
		return ret
	}
	return *o.SecretId
}

// GetSecretIdOk returns a tuple with the SecretId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TencentCloudConfig) GetSecretIdOk() (*string, bool) {
	if o == nil || IsNil(o.SecretId) {
		return nil, false
	}
	return o.SecretId, true
}

// HasSecretId returns a boolean if a field has been set.
func (o *TencentCloudConfig) HasSecretId() bool {
	if o != nil && !IsNil(o.SecretId) {
		return true
	}

	return false
}

// SetSecretId gets a reference to the given string and assigns it to the SecretId field.
func (o *TencentCloudConfig) SetSecretId(v string) {
	o.SecretId = &v
}

// GetSecretKey returns the SecretKey field value if set, zero value otherwise.
func (o *TencentCloudConfig) GetSecretKey() string {
	if o == nil || IsNil(o.SecretKey) {
		var ret string
		return ret
	}
	return *o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TencentCloudConfig) GetSecretKeyOk() (*string, bool) {
	if o == nil || IsNil(o.SecretKey) {
		return nil, false
	}
	return o.SecretKey, true
}

// HasSecretKey returns a boolean if a field has been set.
func (o *TencentCloudConfig) HasSecretKey() bool {
	if o != nil && !IsNil(o.SecretKey) {
		return true
	}

	return false
}

// SetSecretKey gets a reference to the given string and assigns it to the SecretKey field.
func (o *TencentCloudConfig) SetSecretKey(v string) {
	o.SecretKey = &v
}

func (o TencentCloudConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TencentCloudConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SecretId) {
		toSerialize["secretId"] = o.SecretId
	}
	if !IsNil(o.SecretKey) {
		toSerialize["secretKey"] = o.SecretKey
	}
	return toSerialize, nil
}

type NullableTencentCloudConfig struct {
	value *TencentCloudConfig
	isSet bool
}

func (v NullableTencentCloudConfig) Get() *TencentCloudConfig {
	return v.value
}

func (v *NullableTencentCloudConfig) Set(val *TencentCloudConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableTencentCloudConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableTencentCloudConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTencentCloudConfig(val *TencentCloudConfig) *NullableTencentCloudConfig {
	return &NullableTencentCloudConfig{value: val, isSet: true}
}

func (v NullableTencentCloudConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTencentCloudConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


