/*
Core APIs

universalmacro

API version: 0.0.2
Contact: chenyunda218@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AdminList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AdminList{}

// AdminList Account list
type AdminList struct {
	Items []Admin `json:"items"`
	Pagination Pagination `json:"pagination"`
}

type _AdminList AdminList

// NewAdminList instantiates a new AdminList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAdminList(items []Admin, pagination Pagination) *AdminList {
	this := AdminList{}
	this.Items = items
	this.Pagination = pagination
	return &this
}

// NewAdminListWithDefaults instantiates a new AdminList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAdminListWithDefaults() *AdminList {
	this := AdminList{}
	return &this
}

// GetItems returns the Items field value
func (o *AdminList) GetItems() []Admin {
	if o == nil {
		var ret []Admin
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *AdminList) GetItemsOk() ([]Admin, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *AdminList) SetItems(v []Admin) {
	o.Items = v
}

// GetPagination returns the Pagination field value
func (o *AdminList) GetPagination() Pagination {
	if o == nil {
		var ret Pagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *AdminList) GetPaginationOk() (*Pagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *AdminList) SetPagination(v Pagination) {
	o.Pagination = v
}

func (o AdminList) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AdminList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["pagination"] = o.Pagination
	return toSerialize, nil
}

func (o *AdminList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"items",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAdminList := _AdminList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAdminList)

	if err != nil {
		return err
	}

	*o = AdminList(varAdminList)

	return err
}

type NullableAdminList struct {
	value *AdminList
	isSet bool
}

func (v NullableAdminList) Get() *AdminList {
	return v.value
}

func (v *NullableAdminList) Set(val *AdminList) {
	v.value = val
	v.isSet = true
}

func (v NullableAdminList) IsSet() bool {
	return v.isSet
}

func (v *NullableAdminList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAdminList(val *AdminList) *NullableAdminList {
	return &NullableAdminList{value: val, isSet: true}
}

func (v NullableAdminList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAdminList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


