/*
Core APIs

universalmacro

API version: 0.0.2
Contact: chenyunda218@gmail.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ServerConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServerConfig{}

// ServerConfig struct for ServerConfig
type ServerConfig struct {
	Port *string `json:"port,omitempty"`
	JwtSecret *string `json:"jwtSecret,omitempty"`
}

// NewServerConfig instantiates a new ServerConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServerConfig() *ServerConfig {
	this := ServerConfig{}
	return &this
}

// NewServerConfigWithDefaults instantiates a new ServerConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServerConfigWithDefaults() *ServerConfig {
	this := ServerConfig{}
	return &this
}

// GetPort returns the Port field value if set, zero value otherwise.
func (o *ServerConfig) GetPort() string {
	if o == nil || IsNil(o.Port) {
		var ret string
		return ret
	}
	return *o.Port
}

// GetPortOk returns a tuple with the Port field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerConfig) GetPortOk() (*string, bool) {
	if o == nil || IsNil(o.Port) {
		return nil, false
	}
	return o.Port, true
}

// HasPort returns a boolean if a field has been set.
func (o *ServerConfig) HasPort() bool {
	if o != nil && !IsNil(o.Port) {
		return true
	}

	return false
}

// SetPort gets a reference to the given string and assigns it to the Port field.
func (o *ServerConfig) SetPort(v string) {
	o.Port = &v
}

// GetJwtSecret returns the JwtSecret field value if set, zero value otherwise.
func (o *ServerConfig) GetJwtSecret() string {
	if o == nil || IsNil(o.JwtSecret) {
		var ret string
		return ret
	}
	return *o.JwtSecret
}

// GetJwtSecretOk returns a tuple with the JwtSecret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServerConfig) GetJwtSecretOk() (*string, bool) {
	if o == nil || IsNil(o.JwtSecret) {
		return nil, false
	}
	return o.JwtSecret, true
}

// HasJwtSecret returns a boolean if a field has been set.
func (o *ServerConfig) HasJwtSecret() bool {
	if o != nil && !IsNil(o.JwtSecret) {
		return true
	}

	return false
}

// SetJwtSecret gets a reference to the given string and assigns it to the JwtSecret field.
func (o *ServerConfig) SetJwtSecret(v string) {
	o.JwtSecret = &v
}

func (o ServerConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServerConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Port) {
		toSerialize["port"] = o.Port
	}
	if !IsNil(o.JwtSecret) {
		toSerialize["jwtSecret"] = o.JwtSecret
	}
	return toSerialize, nil
}

type NullableServerConfig struct {
	value *ServerConfig
	isSet bool
}

func (v NullableServerConfig) Get() *ServerConfig {
	return v.value
}

func (v *NullableServerConfig) Set(val *ServerConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableServerConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableServerConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServerConfig(val *ServerConfig) *NullableServerConfig {
	return &NullableServerConfig{value: val, isSet: true}
}

func (v NullableServerConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServerConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


